// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddApp(arg1, arg2) {
  return window['go']['main']['App']['AddApp'](arg1, arg2);
}

export function AdoptVaultPath(arg1) {
  return window['go']['main']['App']['AdoptVaultPath'](arg1);
}

export function CheckVaultDir() {
  return window['go']['main']['App']['CheckVaultDir']();
}

export function ChooseVaultPath() {
  return window['go']['main']['App']['ChooseVaultPath']();
}

export function CopyVaultTo(arg1) {
  return window['go']['main']['App']['CopyVaultTo'](arg1);
}

export function GetDiffPair(arg1, arg2) {
  return window['go']['main']['App']['GetDiffPair'](arg1, arg2);
}

export function GetLicenseText() {
  return window['go']['main']['App']['GetLicenseText']();
}

export function GetMachineInfo() {
  return window['go']['main']['App']['GetMachineInfo']();
}

export function GetMirrorRows() {
  return window['go']['main']['App']['GetMirrorRows']();
}

export function GetRecentActivity() {
  return window['go']['main']['App']['GetRecentActivity']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetUndoInfo(arg1) {
  return window['go']['main']['App']['GetUndoInfo'](arg1);
}

export function MoveVaultTo(arg1) {
  return window['go']['main']['App']['MoveVaultTo'](arg1);
}

export function PickFiles() {
  return window['go']['main']['App']['PickFiles']();
}

export function PickFolders() {
  return window['go']['main']['App']['PickFolders']();
}

export function PreviewPaths(arg1) {
  return window['go']['main']['App']['PreviewPaths'](arg1);
}

export function ProbeVaultPath(arg1) {
  return window['go']['main']['App']['ProbeVaultPath'](arg1);
}

export function RestoreApp(arg1) {
  return window['go']['main']['App']['RestoreApp'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanVaultOrphans() {
  return window['go']['main']['App']['ScanVaultOrphans']();
}

export function UndoRestore(arg1) {
  return window['go']['main']['App']['UndoRestore'](arg1);
}

export function UpdateFromSource(arg1) {
  return window['go']['main']['App']['UpdateFromSource'](arg1);
}

export function UseVaultPath(arg1) {
  return window['go']['main']['App']['UseVaultPath'](arg1);
}
