// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddApp(arg1:string,arg2:Array<string>):Promise<void>;

export function AdoptVaultPath(arg1:string):Promise<void>;

export function ChooseVaultPath():Promise<string>;

export function CopyVaultTo(arg1:string):Promise<void>;

export function GetLicenseText():Promise<string>;

export function GetSettings():Promise<main.Settings>;

export function ListApps():Promise<Array<main.ManifestApp>>;

export function MoveVaultTo(arg1:string):Promise<void>;

export function PickFiles():Promise<Array<string>>;

export function ProbeVaultPath(arg1:string):Promise<main.VaultProbe>;

export function SaveSettings(arg1:main.Settings):Promise<void>;
